/*
Copyright 2017 The Caicloud KubeFlow Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// This file was automatically generated by informer-gen

package v1alpha1

import (
	time "time"

	kubeflow_v1alpha1 "github.com/caicloud/kubeflow-clientset/apis/kubeflow/v1alpha1"
	clientset "github.com/caicloud/kubeflow-clientset/clientset"
	v1alpha1 "github.com/caicloud/kubeflow-clientset/listers/kubeflow/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	internalinterfaces "k8s.io/client-go/informers/internalinterfaces"
	kubernetes "k8s.io/client-go/kubernetes"
	cache "k8s.io/client-go/tools/cache"
)

// TFJobInformer provides access to a shared informer and lister for
// TFJobs.
type TFJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.TFJobLister
}

type tFJobInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

func newTFJobInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	sharedIndexInformer := cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.KubeflowV1alpha1().TFJobs(v1.NamespaceAll).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.KubeflowV1alpha1().TFJobs(v1.NamespaceAll).Watch(options)
			},
		},
		&kubeflow_v1alpha1.TFJob{},
		resyncPeriod,
		cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc},
	)

	return sharedIndexInformer
}

func (f *tFJobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kubeflow_v1alpha1.TFJob{}, func(client kubernetes.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
		// panic if client is not *kubernetes.Clientset
		return newTFJobInformer(client.(clientset.Interface), resyncPeriod)
	})
}

func (f *tFJobInformer) Lister() v1alpha1.TFJobLister {
	return v1alpha1.NewTFJobLister(f.Informer().GetIndexer())
}
